routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/**
 * Landing
 */

//payment.callbackRoute::get('/test', 'InvestController@testMailChimp');

Route::get('reactivate/{id}', 'UserController@reactivate');


Route::view('/', 'welcome');
Route::get('/terms-and-conditions', 'HomeController@tandc')->name('users.tandc');
Route::get('/corporate-bylaw', 'HomeController@bylaw')->name('users.bylaw');
Route::get('/getting-started', 'HomeController@gettingStarted')->name('users.getting.started')->middleware('auth');

/**
 * Login & Registration
 */
Route::get('/register/request', 'Auth\RegisterController@request')->name('register.request');
Route::post('/register/request', 'ReferralController@store')->name('request.store');
Route::get('/register/account', 'Auth\RegisterController@registerAccount')->name('register.account');
Route::post('/register/referral', 'Auth\RegisterController@referralVerification')->name('referral.verify');

Route::get('/logout', 'Auth\LoginController@logout');

Auth::routes();

Route::post('/register', 'Auth\RegisterController@create')->name('register');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');

/**
 * Dashboard
 */
Route::get('/home', 'HomeController@index')->name('users.home')->middleware('auth');

/**
 * Help, Contact/Messaging
 */
Route::get('/contact', 'MessageController@index')->name('users.contact')->middleware('auth');

Route::get('/messages', 'MessageController@index')->name('messages.index')->middleware('admin', 'auth');
Route::get('/messages/show', 'MessageController@show')->name('messages.show')->middleware('admin', 'auth');
Route::post('/message', 'MessageController@store')->name('users.message')->middleware('auth');
Route::get('/message/delete/{id}', 'MessageController@delete')->name('message.delete')->middleware('auth');

Route::post('/message/broadcast', 'MessageController@broadcast')->name('message.broadcast')->middleware('auth');

Route::get('/help', 'HomeController@help')->name('users.help')->middleware('auth');

/**
 * Pools and history
 */
Route::get('/pools/{pool}/invest', 'InvestController@create')->name('pools.create')->middleware('auth');
Route::get('/pools/history', 'InvestController@show')->name('pools.show')->middleware('auth');
Route::get('/pools/{pool}/history', 'InvestController@show')->name('pools.pool.show')->middleware('auth');
Route::get('/investment/details/{number}', 'InvestController@investment')->name('investment.show')->middleware('auth');

/**
 * AdminFee
 */
Route::get('pools/adminfees/renew/{pool}', 'AdminFeesController@renew')->name('adminfees.renew')->middleware('auth');
Route::post('pools/adminfees/renew/callback', 'AdminFeesController@renewCallback')->name('adminfees.renew.callback')->middleware('auth');

/**
 * Payment Routes
 */
Route::post('/pools/invest', 'InvestController@store')->name('pools.store')->middleware('auth');
Route::post('pools/invest/payment/callback', 'InvestController@handlePaymentGatewayCallback')->name('payment.callback'); //method is POST for ravepay
Route::get('pools/invest/payment/callback', 'InvestController@handlePaymentGatewayCallback')->name('payment.callback'); //method is GET for paystack

/**
 * Referral
 */
Route::get('/referrals', 'ReferralController@index')->name('referrals.index')->middleware('auth');
Route::post('/referrals/invite', 'ReferralController@invite')->name('referrals.invite')->middleware('auth');
Route::get('/referrals/history', 'ReferralController@history')->name('referrals.history')->middleware('auth');
Route::get('/referrals/noreferral', 'ReferralController@noreferral')->name('referrals.noreferral')->middleware('admin', 'auth');
Route::post('/referrals/noreferral/invite', 'ReferralController@noreferralInvite')->name('referrals.noreferral.invite')->middleware('auth');

/**
 * Transactions
 */
Route::get('/transactions', 'TransactionController@index')->name('transactions.index')->middleware('auth');
Route::get('/transactions/create', 'TransactionController@create')->name('transactions.create')->middleware('admin', 'auth');
Route::post('/transactions', 'TransactionController@store')->name('transactions.store')->middleware('admin', 'auth');
Route::get('/transactions/{transaction}/edit', 'TransactionController@edit')->name('transactions.edit')->middleware('admin', 'auth');
Route::put('/transactions/{transaction}', 'TransactionController@update')->name('transactions.update')->middleware('admin', 'auth');
Route::delete('/transactions/{transaction}', 'TransactionController@destroy')->name('transactions.destroy')->middleware('admin', 'auth');

/**
 * Log
 */
Route::get('/logs', 'LogController@index')->name('logs.index')->middleware('auth');

/**
 * Volition Blue & Categories
 */
Route::resource('/pools/blue', 'BlueController')->middleware('auth');
Route::resource('blue/categories', 'BlueCategoryController')->middleware('admin', 'auth');

/**
 * Volition Privilege & Business
 */
Route::get('/pools/privilege', 'InvestController@privilege')->name('privilege')->middleware('auth');
Route::post('/pools/privilege', 'InvestController@privilegeRegister')->name('privilege.register')->middleware('auth');

Route::get('/pools/business', 'InvestController@business')->name('business')->middleware('auth');
Route::post('/pools/business', 'InvestController@businessRegister')->name('business.register')->middleware('auth');

/**
 * Portfolio
 */
Route::resource('/portfolio', 'PortfolioController')->middleware('admin', 'auth');

/**
 * Settings
 */
Route::get('/settings', 'SettingController@index')->name('settings.index')->middleware('auth');
Route::post('/settings/update', 'SettingController@update')->name('settings.update')->middleware('auth');
Route::post('/settings/user', 'SettingController@updateUser')->name('settings.user')->middleware('auth');
Route::post('/settings/password', 'SettingController@updatePassword')->name('settings.password')->middleware('auth');
Route::get('/settings/pool', 'SettingController@getPool')->middleware('auth');
Route::post('/settings/pool', 'SettingController@updatePool')->name('settings.pool')->middleware('auth');

/**
 * Users Management
 */
Route::get('/users/archived', 'UserController@trashed')->name('users.archived')->middleware('admin', 'auth');
Route::get('/users/unarchive/{id}', 'UserController@untrash')->name('users.unarchive')->middleware('admin', 'auth');
Route::resource('/users', 'UserController')->middleware('admin', 'auth');
Route::get('/users/transaction/{user}', 'UserController@transactions')->name('users.transactions')->middleware('admin', 'auth');
Route::get('/users/referrals/{user}', 'UserController@referrals')->name('users.referrals')->middleware('admin', 'auth');
Route::get('/users/logs/{user}', 'UserController@logs')->name('users.logs')->middleware('admin', 'auth');
Route::get('/users/pools/{user}', 'UserController@pools')->name('users.pools')->middleware('admin', 'auth');
Route::get('/users/pools/create/{user}', 'UserController@poolCreate')->name('users.pools.create')->middleware('admin', 'auth');
Route::get('/users/pools/edit/{pool}', 'UserController@poolEdit')->name('users.pools.edit')->middleware('admin', 'auth');
Route::put('/users/pools/update/{pool}', 'UserController@poolUpdate')->name('users.pools.update')->middleware('admin', 'auth');
Route::delete('/users/pools/delete/{pool}', 'UserController@poolDestroy')->name('users.pools.destroy')->middleware('admin', 'auth');
Route::post('/users/pools/store', 'UserController@poolStore')->name('users.pools.store')->middleware('admin', 'auth');


Route::get(
    '/data/download/user_data',
    [
        'as' => 'data/download/user_data',
        'uses' => 'UserController@getMainUserData'
    ]
);

Route::get(
    '/data/download/investment_data',
    [
        'as' => 'data/download/investment_data',
        'uses' => 'InvestController@getMainInvestmentData'
    ]
);

Route::get(
    '/data/download/transaction_data',
    [
        'as' => 'data/download/transaction_data',
        'uses' => 'TransactionController@getMainTransactionData'
    ]
);

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Database\Eloquent\SoftDeletes;

use App\Subscription;
use App\Pool;
use Carbon\Carbon;

class User extends Authenticatable
{
    use Notifiable;
    use SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $guarded = [];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'isAdmin' => 'boolean',
    ];

    /**
     * The attributes that are date mutable.
     *
     * @var array
     */
    protected $dates = ['created_at', 'deleted_at'];

    /**
     * Retrieve messages that belong to user.
     *
     * @return boolean
     */
    public function messages() {
        return $this->hasMany('App\Message');
    }

    /**
     * Retrieve messages that belong to user.
     *
     * @return boolean
     */
    public function referrals() {
        return $this->hasMany('App\Referral');
    }

    /**
     * The attributes would help check if a user KYC details are filled.
     *
     * @return boolean 
     */
    public function getIsKycAttribute() {
        if ($this->account_number == null || $this->account_bank == null || $this->account_name == null) {
            return false;
        }
        return true;
    }

    /**
     * The attributes would help check if a user KYC details are filled.
     *
     * @return boolean
     */
    public function getFullnameAttribute() {
        return $this->firstname . ' ' . $this->lastname;
    }

    /**
     * The attributes would help check if a user KYC details are filled.
     *
     * @return boolean 
     */
    public function getHasActiveSubscriptionAttribute() {
        $subscriptions_count = Subscription::where('user_id', '=', $this->id)->whereDate('end_date', '>', Carbon::now()->toDateString())->count();
        
        if ($subscriptions_count > 0) {
            return true;
        }
        return false;
    }


    public function getActiveSubscriptionAttribute() {
        $latest = Subscription::where('user_id', $this->id)->whereDate('end_date', '>', Carbon::now()->toDateString())->first();

       if(!$latest){
           return 'x';
       }else{
           $pool = Pool::where('id', $latest->pool_id)->first();
           return $pool->name;
       }

    }

    /**
     * Retrieve wallet balance that belong to user.
     *
     * @return boolean
     */
    public function wallet() {
        return $this->hasOne('App\Wallet');
    }
}

resources/views/users/index.blade.php
@extends('layouts.app')

@section('content')

<div class="row">
    <div class="col-sm-9 col-md-12">
        <h1 class="sub-header">Users</h1>
    </div>
</div>
<!-- Second section -->
<div class="row">
    <div class="col-xs-12 col-md-12">
        <div class="row">
            <div class="col-md-12">
                <span class="card-title">View list of all registered users</span>
                <br>
                <a 
                  href="{{ URL::route('data/download/user_data') }}"
                  style=" margin-bottom:-10px">
                    <button style="padding:7px; margin-bottom:-10px" class="btn btn-gold"> CSV </button>
                </a>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <!-- table card -->
                <table id="table" style="margin-top: 10px">
                    <thead>
                        <tr>
                            <th scope="col" aria-live="assertive">Joined</th>
                            <th scope="col" aria-live="assertive">Name</th>
                            <th scope="col" aria-live="assertive">Email</th>
                            <th scope="col" aria-live="assertive">Mobile No</th>
                            <th scope="col" aria-live="assertive">Subscription</th>
                            <th scope="col" aria-live="assertive">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @if(!empty($users))
                            @foreach($users as $user)
                                <tr>
                                    <td data-label="Joined"><p>{{ $user->created_at->format('j M Y') }}</p></td>
                                    <td data-label="Name">{{ $user->firstname }} {{ $user->lastname }}</td>
                                    <td data-label="Email">{{ $user->email }}</td>
                                    <td data-label="Mobile No" aria-live="assertive">{{ $user->phone }}</td>
                                    <td data-label="Subscription" aria-live="assertive">{{ $user->activeSubscription }}</td>
                                    <td data-label="Action" aria-live="assertive"><a href="{{ route('users.show', $user->id) }}" class="btn btn-xs btn-stroke-gold">View details</a></td>
                                </tr>
                            @endforeach
                        @else
                            <tr>
                                <td data-label="Status" colspan="5">No registered users found.</td>
                            </tr>
                        @endif
                    </tbody>
                </table>
            </div>
            <div id="search" class="search-wrapper">
                <form action="{{ route('users.index') }}" method="GET">
                    <label>
                        <input type="search" name="q" placeholder="Search Users" aria-controls="datatable">
                    </label>
                </form>
            </div>
        </div>
    </div>
    <script>
        $(document).ready(function() {
            $('#table').DataTable({
                "pageLength": 15,
                'columnDefs': [
                  { type: 'html-num', targets: 0}
                ]
            });
        });
    </script>
</div>
@endsection

resources/views/users/trashed.blade.php
@extends('layouts.app')

@section('content')

    <div class="row">
        <div class="col-sm-9 col-md-12">
            <h1 class="sub-header">Archived Users</h1>
        </div>
    </div>
    <!-- Second section -->
    <div class="row">
        <div class="col-xs-12 col-md-12">
            <div class="row">
                <div class="col-md-12">
                    <span class="card-title">View list of all archived users</span>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <!-- table card -->
                    <table id="table" class="">
                        <thead>
                        <tr>
                            <th scope="col" aria-live="assertive">Joined</th>
                            <th scope="col" aria-live="assertive">Name</th>
                            <th scope="col" aria-live="assertive">Email</th>
                            <th scope="col" aria-live="assertive">Mobile No</th>
                            <th scope="col" aria-live="assertive">Subscription</th>
                            <th scope="col" aria-live="assertive">Action</th>
                        </tr>
                        </thead>
                        <tbody>
                        @if(!empty($users))
                            @foreach($users as $user)
                                <tr>
                                    <td data-label="Joined">{{ $user->created_at->format('j M Y') }}</td>
                                    <td data-label="Name">{{ $user->firstname }} {{ $user->lastname }}</td>
                                    <td data-label="Email">{{ $user->email }}</td>
                                    <td data-label="Mobile No" aria-live="assertive">{{ $user->phone }}</td>
                                    <td data-label="Subscription" aria-live="assertive">{{ $user->activeSubscription }}</td>
                                    <td data-label="Action" aria-live="assertive"><a href="{{ route('users.unarchive', $user->id) }}" class="btn btn-xs btn-stroke-gold">Unarchive</a></td>
                                </tr>
                            @endforeach
                        @else
                            <tr>
                                <td data-label="Status" colspan="5">No archived user found.</td>
                            </tr>
                        @endif
                        </tbody>
                    </table>
                </div>
                <div id="search" class="search-wrapper">
                    <form action="{{ route('users.index') }}" method="GET">
                        <label>
                            <input type="search" name="q" placeholder="Search Users" aria-controls="datatable">
                        </label>
                    </form>
                </div>
            </div>
        </div>
        <script>
            $(document).ready(function() {
                var table = $('#table').DataTable({
                    "pageLength": 15
                });
            });
        </script>
    </div>
@endsection

resources/views/users/user.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-sm-9 col-md-12">
            <h1 class="sub-header">{{ $user->firstname }} {{ $user->lastname }}</h1>
            <form action="{{ route('users.destroy', $user->id) }}" method="post" id="deleteUserForm">
                {{ csrf_field() }}
                <input type="hidden" name="_method" value="DELETE">
            </form>
            <button onclick="return ConfirmDelete()" type="submit" form="deleteUserForm" class="btn-gold-xs pull-right" style="margin-right:10px;">Archive User</button>
        </div>
    </div>

    <!-- User Profile -->
    <div class="row"><div class="col-xs-12"><span class="card-title">User Profile</span></div></div>
    <div class="row">
        <div id="user-details-info" class="col-xs-12 col-md-6">
            <div class="table-box">
                <dl class="horizontal-dl-2">
                    <dt>First Name</dt>
                    <dd>{{ $user->firstname }}</dd>
                    <dt>Last name</dt>
                    <dd>{{ $user->lastname }}</dd>
                    <dt>Gender</dt>
                    <dd>{{ $user->gender }}</dd>
                    <dt>Occupation</dt>
                    <dd>{{ $user->occupation }}</dd>
                    <dt>Industry</dt>
                    <dd>{{ $user->industry }}</dd>
                    <dt>Phone number</dt>
                    <dd>{{ $user->phone }}</dd>
                    <dt>Email</dt>
                    <dd class="email-dd">{{ $user->email }}</dd>
                    <dt>Address</dt>
                    <dd>{{ $user->city }}</dd>
                    @if($user->isReferred)
                        <dt>Referred by</dt>
                        <dd><a href="{{ url('users/'.$ref_user_id) }}">{{ $ref_full_name }}</a></dd>
                    @endif
                </dl>
            </div>
        </div>
        <div id="user-details-info" class="col-xs-12 col-md-6">
            <div class="table-box">
                <dl class="horizontal-dl-2">
                    <dt>Bank Name</dt>
                    <dd>{{ $user->account_bank }}</dd>
                    <dt>Account Number</dt>
                    <dd>{{ $user->account_number }}</dd>
                    <dt>Account Name</dt>
                    <dd>{{ $user->account_name }}</dd>
                    <dt>BVN</dt>
                    <dd>{{ $user->account_bvn }}</dd>
                    <dt>Next of Kin Name</dt>
                    <dd>{{ $user->nok_name }}</dd>
                    <dt>Next of Kin Email Address</dt>
                    <dd class="email-dd">{{ $user->nok_email }}</dd>
                    <dt>Next of Kin Phone Number</dt>
                    <dd>{{ $user->nok_phone }}</dd>
                    <dt>Next of Kin Address</dt>
                    <dd>{{ $user->nok_address }}</dd>
                </dl>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-xs-12">
            <span class="card-title">Pool</span>
            <a href="{{ route('users.pools', $user->id) }}" class="btn-gold-xs pull-right">View more</a>
            <a href="{{ route('users.pools.create', $user->id) }}" class="btn-gold-xs pull-right" style="margin-right:10px;">Add Subscription</a>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12 col-md-3">
            <div class="box">
                <div class="row">
                    <div class="col-xs-12 text-center">
                        <p class="desc-text">Volition Green</p>
                        <h1 class="green-text">{{ $metadata['green_count'] }}</h1>
                        <p class="desc-text">Total subscriptions</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-xs-12 col-md-3">
            <div class="box">
                <div class="row">
                    <div class="col-xs-12 text-center">
                        <p class="desc-text">Volition Red</p>
                        <h1 class="red-text">{{ $metadata['red_count'] }}</h1>
                        <p class="desc-text">Total subscriptions</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-xs-12 col-md-3">
            <div class="box">
                <div class="row">
                    <div class="col-xs-12 text-center">
                        <p class="desc-text">Volition Black</p>
                        <h1 class="black-text">{{ $metadata['black_count'] }}</h1>
                        <p class="desc-text">Total subscriptions</p>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-xs-12 col-md-3">
            <div class="box">
                <div class="row">
                    <div class="col-xs-12 text-center">
                        <p class="desc-text">Priviledge/Business</p>
                        <h1 class="black-text">{{ $metadata['privilege_count'] }}/{{ $metadata['business_count'] }}</h1>
                        <p class="desc-text">Total subscriptions</p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-xs-12 col-md-6">
            <div class="row">
                <div class="col-md-12">
                    <span class="card-title">Transaction History</span>
                    <a href="{{ route('users.transactions', $user->id) }}" class="btn-gold-xs pull-right">View more</a>
                </div>
            </div>
            <div class="col-md-12 table-box">
                <table>
                    <thead>
                    <tr>
                        <th scope="col" aria-live="assertive" style="width: 30%;">Date</th>
                        <th scope="col" aria-live="assertive">Description</th>
                        <th scope="col" aria-live="assertive" style="width: 30%;">Amount</th>
                    </tr>
                    </thead>
                    <tbody>
                    @if(count($transactions) > 0)
                        @foreach($transactions as $transaction)
                            <tr>
                                <td data-label="Date">{{ $transaction->created_at->format('j M Y') }}</td>
                                <td data-label="Description">{{ $transaction->trans_desc }}</td>
                                <td data-label="amount" @if($transaction->trans_type == 0) class="green-text" @else class="red-text" @endif aria-live="assertive">₦{{ number_format($transaction->amount) }}</td>
                            </tr>
                        @endforeach
                    @else
                        <tr>
                            <td data-label="status" colspan="3">There are no transactions</td>
                        </tr>
                    @endif
                    </tbody>
                </table>
            </div>
        </div>
        <div class="col-xs-12 col-md-6">
            <div class="row">
                <div class="col-xs-12">
                    <span class="card-title">Recent Activity</span>
                    <a href="{{ route('users.logs', $user->id) }}" class="btn-gold-xs pull-right">View more</a>
                </div>
            </div>
            <div class="col-md-12 table-box">
                <table>
                    <thead>
                    <tr>
                        <th scope="col" aria-live="assertive" style="width: 20%;">Date</th>
                        <th scope="col" aria-live="assertive">Description</th>
                    </tr>
                    </thead>
                    <tbody>
                    @if(count($logs) > 0)
                        @foreach($logs as $log)
                            <tr>
                                <td data-label="Date">{{ $log->created_at->format('j M Y') }}</td>
                                <td data-label="Description">
                                    @if(Auth::user()->isAdmin) {{ $log->user->firstname }} {{ $log->user->lastname }} @else You @endif
                                    {{ $log->log_desc }}
                                </td>
                            </tr>
                        @endforeach
                    @else
                        <tr>
                            <td data-label="status" colspan="3">There are no activity log</td>
                        </tr>
                    @endif
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <div class="row"><div class="col-xs-12"><span class="card-title">Referral</span></div></div>
    <div class="row">
        <div class="col-xs-12 col-md-6">
            <div class="box">
                <div class="row">
                    <div class="col-xs-12 text-center">
                        <h1 class="black-text">{{ $metadata['referral_count'] }}</h1>
                        <p class="desc-text">Referral Made</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-xs-12 col-md-6">
            <div class="box">
                <div class="row">
                    <div class="col-xs-12 text-center">
                        <h1 class="black-text">₦{{ $wallet->balance }}</h1>
                        <p class="desc-text">Total Referral Income</p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-xs-12">
            <span class="card-title">Referral</span>
            <a href="{{ route('users.referrals', $user->id) }}" class="btn-gold-xs pull-right">View more</a>
        </div>
    </div>
    <div class="col-md-12 table-box">
        <table>
            <thead>
            <tr>
                <th scope="col" aria-live="assertive">Date</th>
                <th scope="col" aria-live="assertive">Email</th>
                <th scope="col" aria-live="assertive">Referrer</th>
                <th scope="col" aria-live="assertive">Referral Code</th>
            </tr>
            </thead>
            <tbody>
            @if(count($referrals) > 0)
                @foreach($referrals as $referral)
                    <tr>
                        <td data-label="Date">{{ $referral->created_at->format('j M Y') }}</td>
                        <td data-label="Email">{{ $referral->email }}</td>
                        <td data-label="Referrer">{{ $referral->user->firstname }} {{ $referral->user->lastname }}</td>
                        <td data-label="Referral Code" aria-live="assertive">{{ $referral->referral_code }}</td>
                    </tr>
                @endforeach
            @else
                <tr><td data-label="Status" colspan="3">No referrals have been made</td></tr>
            @endif
            </tbody>
        </table>
    </div>

    <div class="row">
        <div class="col-xs-12 col-md-6">
            <div class="row"><div class="col-md-12"><span class="card-title">Recent Messages</span></div></div>
            <div class="box">
                <div class="row">
                    <div class="col-xs-12 col-md-12" aria-live="assertive">
                        @if(count($messages) > 0)
                            @foreach($messages as $message)
                                @if($message->type == 0)
                                    <div class="chat-col">
                                        <div class="customer-chat-info">
                                            <span class="customer">You</span>&nbsp;&nbsp;<span class="date-time">{{ $message->created_at->diffForHumans() }}</span>
                                        </div>
                                        <div class="chat-content">{{ $message->body }}</div>
                                    </div>
                                @else
                                    <div class="support-chat-col">
                                        <div class="customer-chat-info">
                                            <span class="support">Support</span>&nbsp;&nbsp;<span class="date-time">{{ $message->created_at->diffForHumans() }}</span>
                                        </div>
                                        <div class="chat-content">{{ $message->body }}</div>
                                    </div>
                                @endif
                            @endforeach
                        @endif

                        <div class="row">
                            <div class="col-xs-12 col-md-12 text-center">
                                <a href="{{ route('messages.show', ['to' => $user->id]) }}" class="btn btn-gold" aria-label="view all user message">View All</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <script>
            function ConfirmDelete() {
                return confirm("Are you sure you want to archive this user?");
            }
        </script>
@endsection