routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/**
 * Landing
 */

//payment.callbackRoute::get('/test', 'InvestController@testMailChimp');

Route::get('reactivate/{id}', 'UserController@reactivate');


Route::view('/', 'welcome');
Route::get('/terms-and-conditions', 'HomeController@tandc')->name('users.tandc');
Route::get('/corporate-bylaw', 'HomeController@bylaw')->name('users.bylaw');
Route::get('/getting-started', 'HomeController@gettingStarted')->name('users.getting.started')->middleware('auth');

/**
 * Login & Registration
 */
Route::get('/register/request', 'Auth\RegisterController@request')->name('register.request');
Route::post('/register/request', 'ReferralController@store')->name('request.store');
Route::get('/register/account', 'Auth\RegisterController@registerAccount')->name('register.account');
Route::post('/register/referral', 'Auth\RegisterController@referralVerification')->name('referral.verify');

Route::get('/logout', 'Auth\LoginController@logout');

Auth::routes();

Route::post('/register', 'Auth\RegisterController@create')->name('register');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');

/**
 * Dashboard
 */
Route::get('/home', 'HomeController@index')->name('users.home')->middleware('auth');

/**
 * Help, Contact/Messaging
 */
Route::get('/contact', 'MessageController@index')->name('users.contact')->middleware('auth');

Route::get('/messages', 'MessageController@index')->name('messages.index')->middleware('admin', 'auth');
Route::get('/messages/show', 'MessageController@show')->name('messages.show')->middleware('admin', 'auth');
Route::post('/message', 'MessageController@store')->name('users.message')->middleware('auth');
Route::get('/message/delete/{id}', 'MessageController@delete')->name('message.delete')->middleware('auth');

Route::post('/message/broadcast', 'MessageController@broadcast')->name('message.broadcast')->middleware('auth');

Route::get('/help', 'HomeController@help')->name('users.help')->middleware('auth');

/**
 * Pools and history
 */
Route::get('/pools/{pool}/invest', 'InvestController@create')->name('pools.create')->middleware('auth');
Route::get('/pools/history', 'InvestController@show')->name('pools.show')->middleware('auth');
Route::get('/pools/{pool}/history', 'InvestController@show')->name('pools.pool.show')->middleware('auth');
Route::get('/investment/details/{number}', 'InvestController@investment')->name('investment.show')->middleware('auth');

/**
 * AdminFee
 */
Route::get('pools/adminfees/renew/{pool}', 'AdminFeesController@renew')->name('adminfees.renew')->middleware('auth');
Route::post('pools/adminfees/renew/callback', 'AdminFeesController@renewCallback')->name('adminfees.renew.callback')->middleware('auth');

/**
 * Payment Routes
 */
Route::post('/pools/invest', 'InvestController@store')->name('pools.store')->middleware('auth');
Route::post('pools/invest/payment/callback', 'InvestController@handlePaymentGatewayCallback')->name('payment.callback'); //method is POST for ravepay
Route::get('pools/invest/payment/callback', 'InvestController@handlePaymentGatewayCallback')->name('payment.callback'); //method is GET for paystack

/**
 * Referral
 */
Route::get('/referrals', 'ReferralController@index')->name('referrals.index')->middleware('auth');
Route::post('/referrals/invite', 'ReferralController@invite')->name('referrals.invite')->middleware('auth');
Route::get('/referrals/history', 'ReferralController@history')->name('referrals.history')->middleware('auth');
Route::get('/referrals/noreferral', 'ReferralController@noreferral')->name('referrals.noreferral')->middleware('admin', 'auth');
Route::post('/referrals/noreferral/invite', 'ReferralController@noreferralInvite')->name('referrals.noreferral.invite')->middleware('auth');

/**
 * Transactions
 */
Route::get('/transactions', 'TransactionController@index')->name('transactions.index')->middleware('auth');
Route::get('/transactions/create', 'TransactionController@create')->name('transactions.create')->middleware('admin', 'auth');
Route::post('/transactions', 'TransactionController@store')->name('transactions.store')->middleware('admin', 'auth');
Route::get('/transactions/{transaction}/edit', 'TransactionController@edit')->name('transactions.edit')->middleware('admin', 'auth');
Route::put('/transactions/{transaction}', 'TransactionController@update')->name('transactions.update')->middleware('admin', 'auth');
Route::delete('/transactions/{transaction}', 'TransactionController@destroy')->name('transactions.destroy')->middleware('admin', 'auth');

/**
 * Log
 */
Route::get('/logs', 'LogController@index')->name('logs.index')->middleware('auth');

/**
 * Volition Blue & Categories
 */
Route::resource('/pools/blue', 'BlueController')->middleware('auth');
Route::resource('blue/categories', 'BlueCategoryController')->middleware('admin', 'auth');

/**
 * Volition Privilege & Business
 */
Route::get('/pools/privilege', 'InvestController@privilege')->name('privilege')->middleware('auth');
Route::post('/pools/privilege', 'InvestController@privilegeRegister')->name('privilege.register')->middleware('auth');

Route::get('/pools/business', 'InvestController@business')->name('business')->middleware('auth');
Route::post('/pools/business', 'InvestController@businessRegister')->name('business.register')->middleware('auth');

/**
 * Portfolio
 */
Route::resource('/portfolio', 'PortfolioController')->middleware('admin', 'auth');

/**
 * Settings
 */
Route::get('/settings', 'SettingController@index')->name('settings.index')->middleware('auth');
Route::post('/settings/update', 'SettingController@update')->name('settings.update')->middleware('auth');
Route::post('/settings/user', 'SettingController@updateUser')->name('settings.user')->middleware('auth');
Route::post('/settings/password', 'SettingController@updatePassword')->name('settings.password')->middleware('auth');
Route::get('/settings/pool', 'SettingController@getPool')->middleware('auth');
Route::post('/settings/pool', 'SettingController@updatePool')->name('settings.pool')->middleware('auth');

/**
 * Users Management
 */
Route::get('/users/archived', 'UserController@trashed')->name('users.archived')->middleware('admin', 'auth');
Route::get('/users/unarchive/{id}', 'UserController@untrash')->name('users.unarchive')->middleware('admin', 'auth');
Route::resource('/users', 'UserController')->middleware('admin', 'auth');
Route::get('/users/transaction/{user}', 'UserController@transactions')->name('users.transactions')->middleware('admin', 'auth');
Route::get('/users/referrals/{user}', 'UserController@referrals')->name('users.referrals')->middleware('admin', 'auth');
Route::get('/users/logs/{user}', 'UserController@logs')->name('users.logs')->middleware('admin', 'auth');
Route::get('/users/pools/{user}', 'UserController@pools')->name('users.pools')->middleware('admin', 'auth');
Route::get('/users/pools/create/{user}', 'UserController@poolCreate')->name('users.pools.create')->middleware('admin', 'auth');
Route::get('/users/pools/edit/{pool}', 'UserController@poolEdit')->name('users.pools.edit')->middleware('admin', 'auth');
Route::put('/users/pools/update/{pool}', 'UserController@poolUpdate')->name('users.pools.update')->middleware('admin', 'auth');
Route::delete('/users/pools/delete/{pool}', 'UserController@poolDestroy')->name('users.pools.destroy')->middleware('admin', 'auth');
Route::post('/users/pools/store', 'UserController@poolStore')->name('users.pools.store')->middleware('admin', 'auth');


Route::get(
    '/data/download/user_data',
    [
        'as' => 'data/download/user_data',
        'uses' => 'UserController@getMainUserData'
    ]
);

Route::get(
    '/data/download/investment_data',
    [
        'as' => 'data/download/investment_data',
        'uses' => 'InvestController@getMainInvestmentData'
    ]
);

Route::get(
    '/data/download/transaction_data',
    [
        'as' => 'data/download/transaction_data',
        'uses' => 'TransactionController@getMainTransactionData'
    ]
);

app/Blue.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Blue extends Model
{
    /**
     * Date attribues
     *
     * @var array
     */
    protected $dates = ['created_at', 'updated_at'];

    /**
     * Get category.
     */
    public function category()
    {
        return $this->belongsTo('App\BlueCategory');
    }
}

app/Pool.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Pool extends Model
{
    /**
     * The attributes that aren't mass assignable.
     *
     * @var array
     */
    protected $guarded = [];

    /**
     * one to one relationship between User and Subscription
     * @return \Illuminate\Database\Eloquent\Relations\belongsTo
     */
    public function subscriptions(){

        return $this->hasMany('App\Subscription');
    }

    /**
     * one to one relationship between User and Pool
     * @return \Illuminate\Database\Eloquent\Relations\belongsTo
     */
    public function portfolio(){

        return $this->hasMany('App\Portfolio');
    }


}

app/Http/Controllers/BlueController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

use App\Blue;
use App\BlueCategory;
use App\Log;
use App\User;
use Mail;
use App\Mail\NewBluePost;

class BlueController extends Controller
{

    /**
     * Get Blue Pool Index.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $metadata = [
            'title' => 'Volition Blue',
            'menu_active' => 'pool',
        ];

        if($request->user()->has_active_subscription || $request->user()->isAdmin) {
            if ($request->has('q')) {
                $search_term = $request->q;
                // Build search query
                if ($request->user()->isAdmin) {
                    $blues = Blue::where('title', 'LIKE', $search_term)
                        ->orWhere('markdown', 'LIKE', $search_term)
                        ->paginate($this->page_limit);
                } else {
                    $blues = Blue::where('title', 'LIKE', $search_term)
                        ->orWhere('markdown', 'LIKE', $search_term)
                        ->orWhere('blue_category_id', '!=', 2)
                        ->paginate($this->page_limit);
                }

            } else {
                //get all blues
                if ($request->user()->isAdmin) {
                    $blues = Blue::orderBy('created_at', 'desc')->paginate($this->page_limit);
                } else {
                    $blues = Blue::where('blue_category_id', '!=', 2)->orderBy('created_at', 'desc')->paginate($this->page_limit);
                }
            }
        } else {
            return redirect()->route('users.home')->with('warning', 'You need to have an active subscription in a pool to access Volition Blue');
        }

        return view('pools.blue.index', compact('blues', 'metadata'));
    }

    /**
     * Get Blue Pool Create Form.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $metadata = [
            'title' => 'Volition Blue',
            'menu_active' => 'pool',
        ];

        $category = BlueCategory::pluck('title', 'id');
        return view('pools.blue.create', compact('category', 'metadata'));
    }

    /**
     * Store Blue Pool Information.
     *
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validation = $this->validation($request->blue);

        $validator = Validator::make($request->all(), $validation);

        if ($validator->fails()) return back()->withInput()->withErrors($validator);

        $data = array_merge(['user_id' => auth()->user()->id], $request->except(['_token']));

        //Store new blue pool information
        Blue::unguard();
        $blue = Blue::create($data);
        Blue::reguard();

        //Log action/event
        Log::create(['user_id' => $request->user()->id, 'log_desc' => 'posted content titled ' . $blue->title]);

        if($blue->blue_category_id != 2) {
            //Send Email Notification of Volition Blue to all subscribed members
            $user = User::all();

            foreach($user as $user) {
                if (!$user->isAdmin) {
                    $mail_data = [
                        'title' => 'New Volition Blue Opportunity',
                        'body' => '<h3>' . $blue->title . '</h3>',
                        'action' => 'Explore opportunity',
                    ];
                    Mail::to($user)->queue(new NewBluePost($mail_data));
                }
            }
            return redirect()->route('blue.index');
        } else {
            return redirect()->route('blue.index');
        }
    }

    /**
     * Show Blue Pool Information.
     *
     * @return View
     */
    public function show(Request $request)
    {
        $metadata = [
            'title' => 'Volition Blue',
            'menu_active' => 'pool',
        ];

        $blue_id = $request->blue;

        $blue = Blue::findOrFail($blue_id);

        return view('pools.blue.show', compact('blue', 'metadata'));
    }

    /**
     * Edit Blue Pool Information.
     *
     * @return \Illuminate\Http\Response
     */
    public function edit(Request $request)
    {
        $metadata = [
            'title' => 'Volition Blue',
            'menu_active' => 'pool',
        ];

        $blue_id = $request->blue;

        $blue = Blue::findOrFail($blue_id);
        $category = BlueCategory::pluck('title', 'id');

        return view('pools.blue.edit', compact('blue', 'category', 'metadata'));
    }

    /**
     * Update Blue Pool Information.
     *
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request)
    {
        $blue_id = $request->blue;

        $blue = Blue::findOrFail($blue_id);

        $validation = $this->validation($blue_id);

        $validator = Validator::make($request->all(), $validation);

        if ($validator->fails()) return back()->withInput()->withErrors($validator);

        $data = $request->except(['_token', '_method']);

        Blue::unguard();
        $blue->update($data);
        Blue::reguard();

        //Log action/event
        Log::create(['user_id' => $request->user()->id, 'log_desc' => 'updated content titled ' . $blue->title]);

        return back()->with('success', 'Post updated successfully');;
    }

    /**
     * Delete Blue Pool Information.
     *
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request)
    {
        $blue_id = $request->blue;

        Blue::findOrFail($blue_id)->delete();

        //Log action/event
        Log::create(['user_id' => $request->user()->id, 'log_desc' => 'deleted post with id ' . $blue_id]);

        return redirect()->route('blue.index');
    }

    /**
     * Get Blue Pool Information Rules.
     *
     * @return array
     */
    protected function validation($blue_id)
    {
        return [
            'title' => 'bail|required|unique:blues,title,'.$blue_id.'|max:150',
        ];
    }

}

resources/views/pools/blue/create.blade.php
@extends('layouts.app')

@section('content')
@if(Auth::user()->isAdmin)
<div class="row">
    <div class="col-sm-9 col-md-12">
        <h1 class="sub-header">Create Post</h1>
    </div>
    <div class="col-xs-12 col-md-12">
        <div class="box">
            {!! Form::open(['route' => ['blue.store'], 'method' => 'POST', 'accept-charset' => 'UTF-8', 'id' => 'blueCreateForm']) !!}
            <div class="row"> 
                <div class="col-xs-12 col-md-6" aria-live="assertive">
                    <div class="form-group form-group-default">
                        <label>Post Title</label>
                        <input name="title" class="form-control form-control-textarea"  required rows="20" cols="50" aria-label="enter your post title">
                    </div>
                </div>
                <div class="col-xs-12 col-md-6">
                    <div class="form-group form-group-default">
                        <label>Categories</label>
                        {{ Form::select('blue_category_id', $category, null, ['class' => 'form-control', 'placeholder' => '', 'aria-label' => 'Select blue post categories']) }}
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 col-md-12" aria-live="assertive">
                    <textarea cols="80" rows="10" name="markdown" id="editor" aria-label="enter your post content"></textarea>
                </div>
            </div>

            <div class="row">
                <div class="col-xs-12 col-md-12 text-right">
                    <button type="submit" form="blueCreateForm" class="btn btn-lg btn-gold" aria-label="publish">Publish</button>
                </div>
            </div>
            {!! Form::close() !!}
        </div>
    </div>
</div>
@endif
@endsection

resources/views/pools/blue/edit.blade.php
@extends('layouts.app')

@section('content')
@if(Auth::user()->isAdmin)
<div class="row">
    <div class="col-sm-9 col-md-12">
        <h1 class="sub-header">Edit Post</h1>
    </div>

    @if(session()->has('success'))
        <div class="col-xs-12 col-md-6">
            <div class="notification-success">{{ session()->get('success') }}</div>
        </div>
    @endif

    <div class="col-xs-12 col-md-12">
        <div class="box">
            {!! Form::model($blue, ['route' => ['blue.update', $blue->id], 'method' => 'PUT', 'accept-charset' => 'UTF-8', 'id' => 'blueUpdateForm']) !!}
            <div class="row">
                <div class="col-xs-12 col-md-6" aria-live="assertive">
                    <div class="form-group form-group-default{{ $errors->has('title') ? ' has-error' : '' }}">
                        <label>Post Title</label>
                        <input name="title" class="form-control" value="{{ $blue->title or old('title') }}" required aria-label="enter your post title">
                        @if ($errors->has('title'))
                            <span class="help-block">
                                <strong>{{ $errors->first('title') }}</strong>
                            </span>
                        @endif
                    </div>
                </div>
                <div class="col-xs-12 col-md-6">
                    <div class="form-group form-group-default">
                        <label>Categories</label>
                        {{ Form::select('blue_category_id', $category, $blue->blue_categories_id, ['class' => 'form-control', 'placeholder' => '', 'aria-label' => 'Select blue post categories']) }}
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 col-md-12" aria-live="assertive">
                    <textarea cols="80" rows="10" name="markdown" id="editor" aria-label="enter your post content">{{ $blue->markdown }}</textarea>
                </div>
            </div>
            {!! Form::close() !!}
            <form action="{{ route('blue.destroy', $blue->id) }}" method="POST" id="blueDeleteForm" class="needs-validation" novalidate="">
                {{ csrf_field() }}
                <input type="hidden" name="_method" value="DELETE">
            </form>
            <div class="row">
                <div class="col-xs-12 col-md-12 text-right">
                    <button onclick="return ConfirmDelete()" type="submit" form="blueDeleteForm" class="btn btn-lg btn-stroke-gold" aria-label="delete" style="margin-right: 50px;">Delete</button>
                    <button type="submit" form="blueUpdateForm" class="btn btn-lg btn-gold" aria-label="update">Update</button>
                </div>
            </div>
        </div>
    </div>
</div>
@endif
@endsection
<script>
    function ConfirmDelete() {
        return confirm("Are you sure you want to delete?");
    }
</script>

resources/views/pools/blue/index.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
    <div class="col-sm-12 col-md-12">
        <div class="row">
            <div class="col-sm-12 col-md-3"><h1 class="sub-header">Volition Blue</h1></div>
            <div class="col-xs-6 col-sm-3 col-md-2">@if(Auth::user()->isAdmin)<a href="{{ route('blue.create') }}" class="btn btn-lg btn-gold" style="margin-top:12px;">New Post</a>@endif</div>
            <div class="col-xs-6 col-sm-3 col-md-2 text-right">@if(Auth::user()->isAdmin)<a href="{{ route('categories.index') }}" class="btn btn-lg btn-stroke-gold" style="margin-top:12px;">Categories</a>@endif</div>
            <div class="col-sm-6 col-md-5">
                <div id="search_filter" class="pull-left search_input">
                    <form action="{{ route('blue.index') }}" method="GET">
                        <label><input type="search" name="q" placeholder="Search opportunities"></label>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <div class="col-xs-12"><span class="card-title">Projects Members May Independently Invest In</span></div>
    @if (count($blues) > 0)
        @foreach($blues as $blue)
            <div class="col-xs-12 col-sm-6 col-md-4">
                <div class="box">
                    <div class="row">
                        <div class="col-xs-12">
                            <div class="content-wrap">
                                <h3 class="inner-topic">{{ $blue->title }}</h3>
                                <p class="text-left">{!! substr($blue->markdown,0,250).'...' !!}</p>
                                <p class="blog-date">{{ $blue->created_at->toFormattedDateString() }}</p>
                            </div>
                            <div class="row">
                                <div class="col-xs-6"> 
                                    <a href="{{ route('blue.show', $blue->id) }}" class="btn btn-stroke-gold">Read more</a>
                                </div>
                                @if(Auth::user()->isAdmin)
                                <div class="col-xs-6 text-right">
                                    <a href="{{ route('blue.edit', $blue->id) }}" class="btn btn-lg btn-gold" aria-label="publish">Edit</a>
                                </div> 
                                @endif
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        @endforeach
    @endif

    <div class="col-xs-12">{{ $blues->links() }}</div>
</div>

@endsection

resources/views/pools/blue/show.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
    <div class="col-sm-9 col-md-6">
        <h1 class="sub-header">{{ $blue->title }}</h1>
    </div>
</div>
<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-7">
        <div class="box">
            {!! $blue->markdown !!}
        </div>
        <a href="{{ URL::previous() }}" class="btn-stroke-gold">Back</a>
    </div>
</div>
@endsection